/*
LA CHEVAUCHEE FANTASTIQUE, 03/12/2023, SARINENA-DUMAS-BRUNET MANQUAT
 */
package lachevauchéefantastique;

/**
 *
 * @author pierr
 */
public class Fenetre_Perdant extends javax.swing.JFrame {
    
    int Difficulte;
    int ModeJeu;
    int Nb_Melange;
    int Position_Vert;
    int Position_Hor;
    int TaillePlateau;

    /**
     * Creates new form Fenetre_Perdant
     */
    public Fenetre_Perdant(int Diff, int Mode, int NbMelange, int PosVert, int PosHor, int Taille, boolean tempsDepasse) {
        initComponents();
        this.Difficulte=Diff;
        this.ModeJeu=Mode;
        this.Nb_Melange=NbMelange;
        this.Position_Hor=PosHor;
        this.Position_Vert=PosVert;
        this.TaillePlateau=Taille;
        Txt_tempsEcoule.setVisible(false);
        if (tempsDepasse==true){
            Txt_tempsEcoule.setVisible(true);
        }
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Quitter = new javax.swing.JButton();
        Txt_tempsEcoule = new javax.swing.JLabel();
        Btn_Rejouer = new javax.swing.JButton();
        Btn_Menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Quitter.setText("Quitter");
        Btn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_QuitterActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 110, -1));

        Txt_tempsEcoule.setForeground(new java.awt.Color(255, 255, 255));
        Txt_tempsEcoule.setText("Le temps est écoulé !");
        getContentPane().add(Txt_tempsEcoule, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 120, 30));

        Btn_Rejouer.setText("Rejouer");
        Btn_Rejouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RejouerActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Rejouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 110, -1));

        Btn_Menu.setText("Menu principal");
        Btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel2.setBackground(new java.awt.Color(102, 204, 0));
        jLabel2.setFont(new java.awt.Font("Shrek", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Je vais mourir, je vais mourir, mourir ...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 330, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/shrek.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_QuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_QuitterActionPerformed

    private void Btn_RejouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RejouerActionPerformed
        // Fermer la fenêtre
        this.dispose();

        // Ouvrir la fenêtre principale avec le niveau de difficulté sélectionné
        Fenetre_Principale fenetrePrincipale = new Fenetre_Principale(this.Difficulte, this.ModeJeu, this.TaillePlateau, this.Position_Hor,this.Position_Vert,this.Nb_Melange);
        fenetrePrincipale.setVisible(true);

        fenetrePrincipale.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_RejouerActionPerformed

    private void Btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_MenuActionPerformed
        // Fermer la fenêtre
        this.dispose();
        
        // Ouvrir le menu
        Fenetre_Demarrer fenetreMenu=new Fenetre_Demarrer();
        fenetreMenu.setVisible(true);
        
        fenetreMenu.setLocationRelativeTo(null);
    }//GEN-LAST:event_Btn_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Perdant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Perdant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Perdant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Perdant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Menu;
    private javax.swing.JButton Btn_Quitter;
    private javax.swing.JButton Btn_Rejouer;
    private javax.swing.JLabel Txt_tempsEcoule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
